### PR TITLE
Implement auth service switching for GitHub Enterprise

### LINKED ISSUE #1793: Its possible connect to github enterprise
Hi, its possible configure extension with different github. (Use of github enterprise)

### PR DESCRIPTION
**Pull request by kabel**
Uses a new, proposed alternative authentication provider (switch) to handle authentication and API queries.

Fixed #1793, #2282.

Depends on microsoft/vscode#115940

Edit: Lastest rebase includes a different approach to the solution that allows both authentication providers to be used simultaneously. Which to query is determined by the remote matching the configured GHE URI.

### CODE REVIEW

**Comment by kabel** [comment]
Local testing results:

image

image

**Comment by mew1033** [comment]
Awesome!

**Comment by lupalby** [comment]
I was able to test the changes using the configuration [here](https://github.com/microsoft/vscode-pull-request-github/issues/1793#issuecomment-778269272) and I can confirm that it works very well with the GHE instance we use at work.
Great work!

**Review by vortechs2000 — COMMENTED** [review]
This working well for me  after following the instructions from https://github.com/microsoft/vscode-pull-request-github/issues/1793#issuecomment-778269272:
* GHE: 2.22
* VSCode 1.53.2
* macOS 10.15.7

**Comment by eschweighofer** [comment]
I was able to test the changes using microsoft/vscode-pull-request-github#1793 and confirm it works very well with our GHE instance
Great work!

**Comment by selcukduman** [comment]
Everyone in our team is now using this since it was posted by @kabel. No issues since. 
GHE:2.21.6 
VS Code: stable channel, now on 1.54.3
OS: MacOS 11.2.3 & Windows 10 1909 (18363.1379)

We would love to see this merged as soon as possible.

**Comment by wbcustc** [comment]
+1, would like to get this change reviewed and merged as soon as possible, the Github enterprise support is so important to us.

**Comment by selcukduman** [comment]
Are there any updates on this? We are using the beta version provided by kabel, but need to reinstall it with each plugin update. All is ok with the beta version so far.

**Comment by mew1033** [comment]
@kabel, any word from the vscode devs on getting this merged in? Thanks for building this feature!

**Comment by kabel** [comment]
>  any word from the vscode devs on getting this merged in? Thanks for building this feature!

You're welcome. No word from upstream. Microsoft must keep them busy.

**Comment by HieuNguyen202** [comment]
I'm using the workaround right now. But as soon as this PR gets merged, I'll introduce this feature to everyone in my team. Hopefully, it will go in soon.

**Review by RMacfarlane — APPROVED** [review]

**Pull request merged**
