### PR TITLE
Use newer node version so that graphql queries work again

### PR DESCRIPTION
**Pull request by alexr00**
Graphql API calls weren't working.

### CODE REVIEW

**Review by RMacfarlane — APPROVED** [review]
Thanks for fixing this!

**Comment by RMacfarlane** [comment]
Actually - this causes the webworker build to fail if you run `yarn compile-web`. I thought the issue was that it was using `cjs` there which is why I did the downgrade, there must just be something missing in the webworker webpack to handle this

**Comment by RMacfarlane** [comment]
Nevermind, there isn't an issue with `cjs`, the `node-fetch` alias just needs to be removed from `browser.webpack.config.js`

**Comment by alexr00** [comment]
Everything builds if I remove the node-fetch alias. Thanks!

**Pull request merged**
