### PR TITLE
Minor indentation fixes

### PR DESCRIPTION
**Pull request by arkon**
Still digging through the code to get started. I assume I can just follow [the regular guide on working on extensions](https://code.visualstudio.com/docs/extensions/developing-extensions) for running/debugging this project?

### CODE REVIEW

**Comment by RMacfarlane** [comment]
@arkon Yep, that's correct. Let us know if you have any issues running it

**Comment by arkon** [comment]
@RMacfarlane I can't seem to actually get it to work in the debug `[Extension Development Host]` instance.

Steps that I've done:
1. Pulled repo
1. Installed VSCode Insiders
1. Installed extension normally and configured it
1. Opened project (extension works fine, I can see PRs)
1. `yarn`
1. `yarn watch`
1. F5 to launch extension in the debug `[Extension Development Host]` instance
1. Noted that the extension is being overridden, according to a notification

But the panel doesn't actually show up in the Source Control sidebar, and it never prompts me to sign in or anything.

**Comment by RMacfarlane** [comment]
Hmm. Can you set a break point in the activate method in `extension.ts` and see if init is being reached? I just checked in a change that might fix this: https://github.com/Microsoft/vscode-pull-request-github/pull/550

**Comment by arkon** [comment]
Alright, I updated Yarn (I was on v1.6.x), redid `yarn`, and it seems to work now. Prior to that, it seemed like the change in #550 didn't have any affect.

**Pull request merged**
