### PR TITLE
fix: label left margin in webview

### PR DESCRIPTION
**Pull request by yiliang114**
Fix Label right margin in webview

### CODE REVIEW

**Comment by yiliang114** [comment]
image

**Comment by alexr00** [comment]
@yiliang114 I'm not able to reproduce the issue shown in the screenshot. Do you have any steps I can use to reproduce it?

**Comment by yiliang114** [comment]
> @yiliang114 I'm not able to reproduce the issue shown in the screenshot. Do you have any steps I can use to reproduce it?

@alexr00  Do you mean that it looks like there is no margin on the right side of the label as in the screenshot?  This gif may be helpful. It seems strange that there is no interval. It should not be handled in this way, is it?

bug12

**Comment by alexr00** [comment]
This is what I see:
image

**Comment by yiliang114** [comment]
> This is what I see: image

@alexr00 Does your screenshot on Firefox ?  

I tried several browsers separately: chrome 110.0.5481.177,  Firefox  109.0.1 and Safari 15.3, It seems that chrome's style is not quite right. I feel that it is caused by the original label.

image

**Pull request closed without merging**
