### PR TITLE
Contribute to SCM Graph item context menu (proposed API in 1.94)

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR implements #6236

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
image

**Comment by gjsjohnmurray** [comment]
Looks like something needs to be done at the VS Code end to "bless" this extension's use of another proposed API.

image

**Comment by gjsjohnmurray** [comment]
@lszomoru good point. I had overlooked that there's a built-in GH one too. If I reimplement this PR over there will you consider taking it?

**Comment by lszomoru** [comment]
Sure, please go ahead. This is something for next milestone though...

**Comment by gjsjohnmurray** [comment]
Replaced by https://github.com/microsoft/vscode/pull/229386

**Pull request closed without merging**
