### PR TITLE
New "Create PR" design

### PR DESCRIPTION
**Pull request by hbons**
Tracking the work for https://github.com/microsoft/vscode-pull-request-github/issues/4403

To do:
- [ ] Loading state
- [x] Icons
- [x] Section actions
- [ ] Commits
- [x] Create button menu
- [ ] Gear icon menu
- [ ] user/label decorations

image

### CODE REVIEW

**Comment by joaomoreno** [comment]
Setting to draft, since it appeared in our #codereview channel.

**Comment by alexr00** [comment]
It appeared in the code review channel by design.

**Review by bpasero — APPROVED** [review]
💯

**Review by alexr00 — APPROVED** [review]

**Comment by joaomoreno** [comment]
> It appeared in the code review channel by design.

Sorry about that then. My decision was based on the unchecked checkboxes in the first post.

**Pull request merged**
