### PR TITLE
Gracefully handle errors where the SSH configuration file is corrupt or malformed

### PR DESCRIPTION
**Pull request by eastwood**
Developer notes:

- Bug is around some presumptious FP composition which doesn't consider errors thrown from outside environment.
- Have filtered out issues where the config resolution is erroneous.
- Would like to write tests, but the particular code path is not accessible by tests. The singleton appears to be making it difficult and debugging tests hasn't been entirely easy with the singletons.
- ~~Will have a go at injecting the config file dependency so that we test the scenario~~

### CODE REVIEW

**Comment by eastwood** [comment]
@microsoft-github-policy-service agree

**Review by alexr00 — APPROVED** [review]
Thanks for the PR! I will merge after the March release.

**Comment by eastwood** [comment]
You're welcome :) I performed some QA on this locally, but had a bit of difficulty hooking into the tests in `protocol.test.ts` due to the singletons. Would you be able to confirm that with a malformed .ssh/config file such as:

```
Host: 
```

The error logs are what you expect? 

This is my first contribution to a vscode extension, so hoping that I used the idiomatic logging mechanism. Criticism is appreciated :)

**Comment by alexr00** [comment]
For this extension, the `Logger` that you used is the best way to do it

**Review by aeschli — APPROVED** [review]

**Pull request merged**
