### PR TITLE
Show pull request id in title

### PR DESCRIPTION
**Pull request by justinliew**
Addresses https://github.com/Microsoft/vscode-pull-request-github/issues/537

### CODE REVIEW

**Comment by justinliew** [comment]
@RMacfarlane what's the process for getting PRs looked at? Also I didn't get a CLA bot on this and I think I need to deal with that. Thanks!

**Comment by RMacfarlane** [comment]
Hmm, I'm not sure why the bot didn't kick in. I'll look into it.

There's not really a formalized process for reviews, right now I'm trying to get to them within a day of their creation, but am also balancing other work 😃

**Comment by justinliew** [comment]
> Hmm, I'm not sure why the bot didn't kick in. I'll look into it.
> 
> There's not really a formalized process for reviews, right now I'm trying to get to them within a day of their creation, but am also balancing other work 😃

Ok - thanks for replying so quickly and for all your hard work! I'm new to the open source stuff but Hacktoberfest has really inspired me to try to find tools I use and help improve them :)

**Comment by RMacfarlane** [comment]
Awesome!

I looked more into the CLA bot, documentation on it says it doesn't trigger on small changes. There's a checkmark next to your commit saying that all CLA requirement are met, so we're good there.

This does clearly fix the problem in #537 but it also takes up more horizontal space, which I'm not sure we want. @misolori @rebornix what do you think, is there another way we could show this info? We could show it in the tooltip, but that's not very useful at a glance. I wish the VSCode tree API allowed setting a description or providing a custom render function for tree items.

**Comment by misolori** [comment]
Thanks for taking a look at this!

I do think that adding it to the front of the string adds visual noise when it's intended to be secondary info, so I think I prefer it being added to the end of the string instead:

image


Ideally if we could add decorations on the line, similar to the git/scm decorations, we could add a different color to make them stand out less, but I'm not sure if that's possible.

**Comment by justinliew** [comment]
image
I think that's a good call; that way if stuff is cut off then it's the PR id, rather than part of the text. Plus, these are short PR ids; I'm sure with larger repos there are 4-5 digit ones which would definitely add unnecessary noise.

**Comment by misolori** [comment]
Thanks! I'd also double-check that it gets added to the tooltip, doesn't look like it was added there as well.

**Pull request merged**
