### PR TITLE
Allow to see commits of a PR without checking out to it

### PR DESCRIPTION
**Pull request by Yuuki77**
Fixes https://github.com/microsoft/vscode-pull-request-github/issues/2201
now you can see the commits without checking out

So I decided to use `files` folder and `commit` folder. 
image

### CODE REVIEW

**Review by RMacfarlane — CHANGES_REQUESTED** [review]
Thanks for taking a look at this!

We need to do some additional work to make sure that showing the files in the commits works. Right now, the `Commits` node assumes that you have already checked out the pull request branch, so you have all of the commits for it locally. It uses git to fill in the file content for these commits (`gitContentProvider.ts`). We would need to instead get the content from GitHub if you don't have the commits locally

**Comment by Yuuki77** [comment]
@RMacfarlane 
Thank you for the feedbacks!
I see!
Can you tell me how to reproduce that kind of issue?
When I tested, I could see the commits in `All`folder 
I thought I did not have commits for these prs

**Comment by RMacfarlane** [comment]
Sure! Here is a way to reproduce the issue:

1. Open a pull request using the extension
2. Open the PR on GitHub.com and then go to the branch it is from. You can click on a file and use the edit button to make a commit on GitHub.com
3. Back in VS Code, refresh the pull request tree
4. Open the new commit node and click on a file

It should show two error notifications saying "We couldn't find commit <commitId>"

**Comment by Yuuki77** [comment]
@RMacfarlane Thank you for the instructions.
Hmm I could not reproduce the issue.
When I clicked the refresh, I can see the new commits. 🤔

**Comment by RMacfarlane** [comment]
Hmm, do you by chance have the `git.autofetch` setting set to true?

**Comment by Yuuki77** [comment]
@RMacfarlane you are right.`git.autofetch` is true in my settings.
let me test when I  set this to false! 💪

**Comment by Yuuki77** [comment]
@RMacfarlane still investigating..
Which function should I call to fetch the commit locally?
This is what I did so far but still not working 😓 
https://github.com/microsoft/vscode-pull-request-github/pull/2245/commits/6a366acd200dff9d3d1425a1ba4f4c205af7bbb9

**Review by toriibby — APPROVED** [review]

**Review by toriibby — APPROVED** [review]

**Comment by toriibby** [comment]
i dont bro im new at this

**Review by toriibby — APPROVED** [review]

**Review by JoaoLobo94 — CHANGES_REQUESTED** [review]
test

**Review by JoaoLobo94 — APPROVED** [review]
test

**Comment by alexr00** [comment]
@Yuuki77 thank you for the PR. As part of our annual GitHub PR and issue clean up, I'm going to close this PR since there hasn't been any activity on it in 2 years. If you still plan to work on it please let me know and I'll re-open it!

**Pull request closed without merging**
