### PR TITLE
[WIP] Feature/copy pr link in header

### PR DESCRIPTION
**Pull request by ashrodan**
## Summary
As discussed in the below issues, this PR attempts to resolve this by adding a copy icon adjacent to the title. When the user clicks the copy icon, the PR URL is copied to the user's clipboard.

Resolves: https://github.com/microsoft/vscode-pull-request-github/issues/1172
Resolves: https://github.com/microsoft/vscode-pull-request-github/issues/1906

*Light (Visual Studio)*
_Extension_Development_Host__-_Pull_Request__755_—_business-intelligence
*Dark (Visual Studio)*
_Extension_Development_Host__-_Pull_Request__755_—_business-intelligence

## RFC
- links is wrapped in `<a>` tag rather than `<button>` (currently done this to avoid the inherent styling that comes with `<button>`)
- Usage of `navigator` to copy to clipboard (unsure if this works on other OS's)
- Copy icon SVG doesn't have the same contrast for darker themes 
- No clear feedback after the user hovers/clicks the icon 

## Other solutions thought of
- Discreetly add a hidden button to the PR title when clicked add to the clipboard
- After creating the PR automatically add the PR link to the clipboard with a notification (just like VS codeshare does)

### CODE REVIEW

**Comment by ashrodan** [comment]
Keen to hear feedback on the direction of this @RMacfarlane

**Comment by RMacfarlane** [comment]
Sorry for the delay, I've just gotten back from vacation. This looks good, I like the approach you're taking!

I'm also not sure how robust using `navigator` is. One potential alternative is to instead use VSCodes `clipboard` API. In the onClick, you could post a message, and then receive it in `pullRequestOverview.ts` and use vscode.env.clipboard.writeText`. This might be overkill, though. @mjbvz, do you know if it's safe to use `navigator.clipboard` directly?

For the contrast issue, I think you need to add `fill: var(--vscode-foreground)` to the css for styling the svg, that variable should update automatically when changing the theme. Maybe you already know about it, but you can run the command "Developer: Open Webview Developer Tools" when the description page is open and use this to play around with the styles of the page.

As you said, having feedback when the icon is clicked would be nice. I like the UI GitHub has for this, where the button briefly turns into a checkmark and then back. Or we could show a notification.

**Comment by rishab-pdx** [comment]
#2203 addresses this! @RMacfarlane @ashrodan FYI

**Comment by RMacfarlane** [comment]
Hey @ashrodan, since I haven't heard back from you, I've gone ahead and merged https://github.com/microsoft/vscode-pull-request-github/pull/2203. Thanks for taking a look at this, though!

**Pull request closed without merging**
