### PR TITLE
Show more details in PR tree view tooltip, closes #568.

### LINKED ISSUE #568: Show more details in tree view tooltip
Right now it just re-displays the PR title, it would be nice to also show the author as sometimes it's not obvious (hard to diff the top and bottom avatars):

image

### PR DESCRIPTION
**Pull request by jerrymajewski**
- Show the PR's `author login name` and `creation date` in the `GitHub Pull Requests` tree node tooltips.

**Before:**

screen shot 2018-10-14 at 12 13 14 pm

**After:**

screen shot 2018-10-14 at 12 13 14 pmb

### CODE REVIEW

**Comment by rebornix** [comment]
I like the idea but I'm a bit reluctant to display time in the PR tooltip, especially when it can be out of date very easily. cc @misolori for review , this is probably the first time we introduce multi line tooltip in this extension.

**Comment by misolori** [comment]
I agree that we should just display the author with no timestamp on a single line.

**Comment by jerrymajewski** [comment]
I updated the tooltip as follows:

screen shot 2018-10-24 at 5 27 59 am

**Comment by misolori** [comment]
We should just append the author to the end of the string after the parenthesis: 
`Closes BLOS-223 (#282) by katwal-dipak`

**Pull request merged**
