### PR TITLE
Issue #3371 | Updated getAuthSessionOptions in case of GitHub Enterprise AuthProvider

### PR DESCRIPTION
**Pull request by jpspringall**
Resolves Unable to Access Enterprise Git Pull Requests #3371

### CODE REVIEW

**Review by alexr00 — APPROVED** [review]
Thank you for the fix!

**Comment by hediet** [comment]
What is the difference between
```ts
getAuthSessionOptions = { ...getAuthSessionOptions, ...{ createIfNone: true, silent: false } };
```
and
```ts
getAuthSessionOptions = { ...getAuthSessionOptions, createIfNone: true, silent: false };
```
?

**Comment by alexr00** [comment]
@hediet I would expect those to do the exact same thing.

**Comment by jpspringall** [comment]
> @hediet I would expect those to do the exact same thing.

That is correct both do the same thing, I just copied the style that was there before

**Pull request merged**
