### PR TITLE
Change icon to more representative icon

### LINKED ISSUE #2280: Replace Icon on the Activity Bar by an Octocat (or anything different to built-in Source Control)
> Searched for duplicated issues, didn't find any

**Situation**: Current Icon for the Activity Bar is extremely similar to already existing menu "Source Control" (check the image)

Captura de pantalla 2020-11-11 a las 11 46 12

**Request**: Change the Activity Bar icon of this extension.
**Suggestion**: I'd go for an Octocat; `Octocat === Github` , besides the icon is already in the repo (https://github.com/microsoft/vscode-pull-request-github/blob/master/resources/icons/github_logo.png)

github_logo

### PR DESCRIPTION
**Pull request by KaiSforza**
Fixes #2280 

`pull-request.png` was extremely similar to the standard "Source Control" tab in vscode, this changes it to one that is much more github.

Dark theme: 
image

Light theme:
image

Light sidebar:
image

### CODE REVIEW

**Comment by KaiSforza** [comment]
This seems to have been the icon at one point when looking at [the readme's first gif](https://github.com/microsoft/vscode-pull-request-github/blob/master/.readme/demo.gif)

**Comment by KaiSforza** [comment]
Any comments on this?

**Comment by RMacfarlane** [comment]
Hey @KaiSforza, sorry for the delayed response!

I agree that this icon does a better job of representing the extension and is also easier to distinguish from the other icons in the activity bar. The reason this icon was changed is because of GitHub codespaces, which introduces its own GitHub icon on the activity bar:

Screen Shot 2020-11-30 at 8 15 30 AM

Maybe an icon that combines the GitHub logo and the git pull icon would work for this scenario, like having the GitHub logo with it at the corner as the codespaces icon does with the VSCode logo. @misolori Do you think that would work?

**Comment by misolori** [comment]
@RMacfarlane I think we'd need to ask the GitHub team as that is modifying their brand logo. My thought is they wouldn't be keen on it since it's not a product/feature.

**Comment by dantman** [comment]
The current icon is actively harmful. It's very hard to distinguish the sidebar panel for making commits (which you need to use very frequently) from the GitHub issues/PR sidebar.

**Review by RMacfarlane — APPROVED** [review]
Thanks @KaiSforza, going to go ahead and merge this now since Codespaces no longer has a conflicting icon!

**Pull request merged**
